In [1]:
import tensorflow as tf 

import pickle
import pandas as pd 
import numpy as np

In [2]:
from tensorflow.keras.models import load_model
##load the trained models,scaler pickle,onehotencoder 
model=load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
import pickle
#load the encoder and scaler 
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo = pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)
with open("scaler",'rb') as file:
    scaler=pickle.load(file)

In [7]:
import pandas as pd
##example input_data 
input_data = {
    "CreditScore":600,
    "Geography" :'France',
    "Gender" : 'Male',
    'Age':40,
    "Tenure":3,
    'Balance' : 60000,
    "NumOfProducts" : 2,
    'HasCrCard':1,
    "IsActiveMember":1,
    'EstimatedSalary':50000
}

#onehot encoding 
geo_encoder = onehot_encoder_geo.transform([[input_data['Geography']]])
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

c:\Users\Dell\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [8]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [9]:
#encode categorical gender 
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [10]:
#concatination one hot encoder
input_df = pd.concat([input_df.drop('Geography', axis=1),geo_encoder_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [11]:
###scaling the input data 
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [12]:
#Prediction churn 
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

array([[0.0383439]], dtype=float32)